networks:
  web:
    external: 'true'
  nox_net: {}

services:
  nox-backend:
    build: .
    env_file: .env
    volumes:
      - ./docker-volumes/nox-backend/uploads:/app/uploads   # ⬅ persistencia
      # - ./docker-volumes/nox-backend/logs:/app/logs        # ⬅ opcional
    expose:
      - "3000"
    networks:
      - web
      - nox_net
    depends_on:
      - postgres
    # ⬇️ Migraciones + node (sin nodemon) para prod
    command: sh -c "npx prisma migrate deploy && node index.js"
    # restart: unless-stopped                                # ⬅ opcional
    labels:
      # Caddy
      caddy: ${APP_HOST}
      caddy.reverse_proxy: "{{upstreams 3000}}"
      # Traefik
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:${APP_HOST}"
      traefik.port: '3000'

  postgres:
    image: postgres:14
    restart: always
    env_file: .env
    networks:
      - nox_net
   # ports:
    #  - "5433:5432"
    volumes:
      - ./docker-volumes/postgres/data:/var/lib/postgresql/data   # ⬅ persistente



